### ISSUE TITLE
Limit must be an integer Code

### ISSUE THREAD

**Issue by lafama** [seangarner/mongo-url-utils#11]
Am trying to get my head around this code in the limit.js file

```
 if (n.toString() !== s){ 
    throw new Error('limit must be an integer');}
```

Why do you have it there?

**Comment by seangarner** [comment]
If I recall I think I put it there because `parseInt` isn't very strict.  For example...

``` js
parseInt("15foobar", 10);
// 15
```

... but I didn't add a test for it, so who knows :confused:

**Comment by seangarner** [comment]
Actually I did add a test (of sorts), it's to throw if the input is a decimal.

``` js
parseInt("1.1", 10)
1
```

Again, because `parseInt` isn't very strict.

**Comment by lafama** [comment]
Wont this handle this case

```
!is.int(n)
```

The problem is that it ((n.toString() !== s)) is failing when i pass an integer instead of a sting

```
1= fails
'1'= passes
```

**Comment by seangarner** [comment]
`parseInt` has already made an integer out of the decimal or garbage that was input.  So `!is.int(n)` isn't going to handle input of `"1.1"` or `1foobar`.

Intended use was for a parsed set of url parameters.  I'm curious how your input has an integer, was it typecast by something?

Can you call `.toString()` on your input as you send it?

**Comment by lafama** [comment]
The initial default value for limit or skip  Example

```
if(limit==undefined){
      limit=100;
    }
```

Well i can always set it to a string but.....just don't feel right. :-).. yet the value should be an integer in the first place

**Comment by seangarner** [comment]
Have you considered setting defaults on the output instead of the input?

``` js
var opts = mongoUrlUtils(...);
if (opts.limit === undefined) opts.limit = 100;
```

**Comment by seangarner** [comment]
I feel fairly comfortable that it shouldn't accept an integer since it's a string parser.  I'd consider supporting default settings as a secondary param but I figured that I don't want to get opinionated on it so for now I've left it up to the consumer to set defaults on the output if they desire.

FWIW I use [mout/object/fillIn](http://moutjs.com/docs/latest/object.html#fillIn) for doing just that.
